# Generated by Django 3.2.7 on 2021-11-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
