# Generated by Django 3.2.7 on 2021-11-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_product_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
