# Generated by Django 3.2.7 on 2021-11-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_product_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.shopowner'),
        ),
    ]
