# Generated by Django 3.2.7 on 2021-11-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_product_shopowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
