# Generated by Django 3.2.7 on 2021-11-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_product_rate'),
        ('ecommerce_web', '0008_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.shopowner'),
        ),
    ]
